### ISSUE TITLE
Rotary encoder requires a module which cannot be installed

### ISSUE THREAD

**Issue by volumio** [volumio/volumio-plugins#136]
@Saiyato 
When I do volumio plugin install I get this error:

npm ERR! notarget No compatible version found: onoff-rotary@^0.2.1

This should be fixed (use another module or link the module as library)

https://github.com/volumio/volumio-plugins/blob/fc328b85e40c56a6554ef6ff8af10a86e9b2555e/plugins/user_interface/rotaryencoder/package.json#L37

**Comment by Saiyato** [comment]
You are correct, I just updated my package.json
