### ISSUE TITLE
Youtube plugin not retrieving stream

### ISSUE THREAD

**Issue by fighne** [volumio/volumio-plugins#138]
Latest Volumio, using PiFi Digi+ with latest YouTube plugin not retrieving audio stream

**Comment by joker5689** [comment]
Hello, i having the same problem on my Raspberry Pi 3 B, HiFiBerry AMP2 with volumio 2.362
Some YouTube songs are playing others not. I already asked for help on the volumio forum, without success. See [https://volumio.org/forum/some-youtube-songs-are-playing-others-not-t8932.html]

**Comment by joker5689** [comment]
Further research showed the YouTube songs that playing have the tag "Album: null".
![volumioyoutubeissue2](https://user-images.githubusercontent.com/32590410/36196238-5bd0a05e-1170-11e8-9d93-7dbaaf0e7321.jpg)

**Comment by mxjeff** [comment]
Same thing for me on rpi2 with volumio v2.348.

I also have an issue on rpi3 with kodi + youtube plugin, [cf. related issue](/jdf76/plugin.video.youtube/issues/285).

**Comment by tsrubar** [comment]
Same for me on RPi 1B+ with PiFi DAC

**Comment by volumio** [comment]
Fixed with https://github.com/volumio/volumio-plugins/commit/a9e848f0dbd700b8b3976372d01b279acb2f4c48
