### ISSUE TITLE
volspotconnect2 not available on x86

### ISSUE THREAD

**Issue by balbuze** [volumio/volumio-plugins#177]
Volspotconnect2 works on x86, but not available on plugin list. Any reason ? The install.sh file detect the cpu and download the required version of librespot. Let me know if something is wrong.

**Comment by ashthespy** [comment]
Needs to be added to the [`plugins.json`](https://github.com/volumio/volumio-plugins/blob/gh-pages/plugins/volumio/i386/plugins.json) for x86.

**Comment by balbuze** [comment]
Same with last official version. The plugin is ready for x86 but not published. @volumio

**Comment by volumio** [comment]
Published to x86 as well!
