### ISSUE TITLE
volumio 2.001 plugin start - stop

### ISSUE THREAD

**Issue by balbuze** [volumio/volumio-plugins#28]
plugin manager behaves weird. If you disable a plugin, you can't re-enable it. The only way is to set it to true in plugin.json

**Comment by macmpi** [comment]
This problem seems to still be there in 2.032

**Comment by balbuze** [comment]
? Really ? It works now for me..

**Comment by macmpi** [comment]
ok, will take time to start fresh from blank image then and check again.

**Comment by volumio** [comment]
It might depend on the plugin you're using. Which plugin is it?

**Comment by macmpi** [comment]
same issue with spop (see earlier edit) & volspotconnect
