### ISSUE TITLE
Updated file for Apple Remote A1294

### ISSUE THREAD

**Issue by mcdonaldajr** [volumio/volumio-plugins#289]
When I use the Volumio IR Remote Controller Plugin, and select Apple Remote A1294 it doesn't work.
I have to use the settings below to get it to work.
I have checked inside the battery compartment of the remote, and it definitely says A1294.
Perhaps you could add this version as a variant?

Many Thanks, Anthony

# Please make this file available to others
# by sending it to <lirc@bartelmus.de>
#
# this config file was automatically generated
# using lirc-0.9.0-pre1(default) on Sun Nov 26 18:41:37 2017
#
# contributed by 
#
# brand:                       /home/volumio/out.conf
# model no. of remote control: Apple Remote A1294
# devices being controlled by this remote:
#

begin remote

  name  /home/volumio/out.conf
  bits            8
  flags SPACE_ENC|CONST_LENGTH
  eps            30
  aeps          100

  header       9052  4439
  one           586  1635
  zero          586   536
  ptrail        586
  repeat       9059  2207
  pre_data_bits   16
  pre_data       0x77E1
  post_data_bits  8
  post_data      0xD8
  gap          106949
  toggle_bit_mask 0x0

      begin codes
          KEY_MENU                 0x40
          KEY_PLAY                 0x7A 0x20
          KEY_LEFT                 0x10
          KEY_RIGHT                0xE0
          KEY_UP                   0xD0
          KEY_DOWN                 0xB0
          KEY_ENTER                0xBA 0x20
      end codes

end remote

**Comment by volumio** [comment]
Can you please open a PR on the plugin?
