### ISSUE TITLE
Spotify no sound with 2.001 on rpi3

### ISSUE THREAD

**Issue by snowf0x** [volumio/volumio-plugins#31]
Hey guys, 
When I try to play a Spotify song, webui show notification music start to play, but play/stop button is not refreshed. However the playing progress circle is showing and time is counting as well.
Most important no sound is come out.  I use iquadld dac

**Comment by smartcris** [comment]
I'm using hifiberry and got the same problem. I'm able to hear the sound if hardware volume is set on the option menu, but when I switch to software volume. Spotify no longer works.
