### ISSUE TITLE
[Touch display] Action popups outside screen

### ISSUE THREAD

**Issue by geek-merlin** [volumio/volumio-plugins#399]
On RasPi with official 7'' DIsplay and Touchscreen Plugin

When i go to the music repository
and tap on to the topmost item,
a action popup with some option opens,
but above and outside of the visible screen,
so i am not able to add that item.

**Comment by gvolt** [comment]
I guess it is the same issue reported here [https://github.com/volumio/Volumio2-UI/issues/524](url) and [https://github.com/volumio/Volumio2-UI/issues/248](url).

**Comment by geek-merlin** [comment]
Yes thanks for that - i only searched this project.

So this is a dup of
https://github.com/volumio/Volumio2-UI/issues/524
