### ISSUE TITLE
youtube limit exceeded

### ISSUE THREAD

**Issue by balbuze** [volumio/volumio-plugins#417]
today I get this message :
`Feb 28 20:22:29 volumio-rpi4 volumio[953]: error: Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=846464762843
Feb 28 20:22:29 volumio-rpi4 volumio[953]: Error: Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=846464762843
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at Request._callback (/data/plugins/music_service/youtube/node_modules/google-auth-library/lib/transporters.js:85:15)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at Request.self.callback (/data/plugins/music_service/youtube/node_modules/request/request.js:185:22)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at emitTwo (events.js:126:13)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at Request.emit (events.js:214:7)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at Request.<anonymous> (/data/plugins/music_service/youtube/node_modules/request/request.js:1154:10)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at emitOne (events.js:116:13)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at Request.emit (events.js:211:7)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at IncomingMessage.<anonymous> (/data/plugins/music_service/youtube/node_modules/request/request.js:1076:12)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at Object.onceWrapper (events.js:313:30)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at emitNone (events.js:111:20)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at IncomingMessage.emit (events.js:208:7)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at endReadableNT (_stream_readable.js:1064:12)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
Feb 28 20:22:29 volumio-rpi4 volumio[953]: at process._tickCallback (internal/process/next_tick.js:180:9)
`

**Comment by volumio** [comment]
See: https://forum.volumio.org/youtube-for-volumio-t6608-320.html#p73133
