### ISSUE TITLE
Plugin Touch Display: use Chromium from archive.raspberrypi.org/debian

### ISSUE THREAD

**Issue by mithat** [volumio/volumio-plugins#42]
The technique currently used by the plugin to get Chromium browser is explored in this [Stack Exchange answer](https://raspberrypi.stackexchange.com/questions/44384/how-to-get-chromium-on-raspberry-3/44397#44397). A comment to that answer indicates the shortcomings of this approach.

According to [another answer](https://raspberrypi.stackexchange.com/questions/44384/how-to-get-chromium-on-raspberry-3/56231#56231) under the same question, Chromium is available in Raspbian if you add the `archive.raspberrypi.org/debian` repository. This would appear to be a better way to get Chromium as it avails itself to standard system updates.

**Comment by macmpi** [comment]
has been fixed. Can be closed now, thanks.
