### ISSUE TITLE
Youtube plugin is not working

### ISSUE THREAD

**Issue by outapzaza** [volumio/volumio-plugins#424]
So already use lastest version and already login
![image](https://user-images.githubusercontent.com/40026698/76222188-d3e10f00-624c-11ea-9263-7b552ce5ac6a.png)

When i try to use youtube function it won't working and retrun "No result"
![image](https://user-images.githubusercontent.com/40026698/76222297-ff63f980-624c-11ea-8c93-33b2b02b8c8c.png)

**Comment by volumio** [comment]
https://github.com/volumio/volumio-plugins/issues/387
