### ISSUE TITLE
"No Results" error when using the YouTube plugin

### ISSUE THREAD

**Issue by adamj-codethink** [volumio/volumio-plugins#430]
I have signed in to the YouTube plugin and allowed access, i have also set some music play lists to public, but the plugin keeps reporting "No Results" when i click any section of the plugin.

Is there anything else i need to enable, or places i could look for logs?

Thanks

**Comment by balbuze** [comment]
Please, Youtube plugin is removed from official plugin because it does not work, so don't use it!
It willl be available when fixed.
Remove it to make search work with other sources.

**Comment by adamj-codethink** [comment]
Thanks, it still appears under my Volumio "plugins" section, i will remove for now

**Comment by balbuze** [comment]
You're right, it still appears. To be fxed. Thanks!

**Comment by volumio** [comment]
Ah, I thought we removed it.. Thanks for reporting..

@balbuze can you please remove it from the gh-pages branch?

**Comment by balbuze** [comment]
done...

**Comment by adamj-codethink** [comment]
i will close this for now :)
