### ISSUE TITLE
Plugin category "Miscelleanea" in plugins.json for i386

### ISSUE THREAD

**Issue by gvolt** [volumio/volumio-plugins#437]
In [plugins.json](https://github.com/volumio/volumio-plugins/blob/ebd7b15f7394a39c5bbc876545110cec02d03659/plugins/volumio/i386/plugins.json#L174) for i386 exists a plugin category "Miscell**e**anea" containing the plugins "LastFM Scrobbler" version 1.1.11 as of 19-2-2018 and "AutoStart" version 1.1.2.

In case this should be a typo: "LastFM Scrobbler" is already part of the category "Miscellanea" (but in version 1.3.4 as of 19-12-2019).

**Comment by balbuze** [comment]
yes I saw this... It should be moved in the correct name/folder... I'll have a look.

**Comment by gvolt** [comment]
[PR](https://github.com/volumio/volumio-plugins/pull/466) sent.
