### ISSUE TITLE
Raspberry Pi doesnt boot (panic) after adding touchscreen plugin

### ISSUE THREAD

**Issue by markcarline** [volumio/volumio-plugins#54]
volumio works fine on the raspberry PI 3 (not sure if it's all Pis) but after adding the official touch screen display plug in it gives a Kernel panic, see:

![img_20170309_125919](https://cloud.githubusercontent.com/assets/2694230/23751335/c1b2789e-04c8-11e7-9bac-661b09fc463d.jpg)

**Comment by iamsi** [comment]
I have the touch working fine on a pi3 how do you have the touch screen connected, do you have the I2C pins connected on the gpio header for example?

**Comment by markcarline** [comment]
Yes, but they are mapped via an IQAudio PI-DigiAmp+ (it's the same pins that are used).

Everything worked yesterday fine, i just re-imaged from as new download today (which seems to use a new IMG file dated 2017-03-07)

**Comment by iamsi** [comment]
remove the i2c pins, if you are using a pi3 it should come over the display flex cable.

**Comment by markcarline** [comment]
Yep tried that (it's only using the gnd & power and still panic)

**Comment by iamsi** [comment]
I just flashed the image from yesterday (volumio-2.118-2017-03-07-pi) and I can replicate the issue. Sorry for wasting your time with the checks, the old image but with the latest updates is what I was using when I first commented.

**Comment by macmpi** [comment]
Please check ongoing debug work [here](https://volumio.org/forum/installing-the-touch-display-plugin-t6032-10.html#p29746).
Not very far from being done I think: just a X.org config issue now, any help appreciated.

**Comment by macmpi** [comment]
Fixed with newer plugin version: you may close this issue. Thanks.

**Comment by markcarline** [comment]
Nice one guys - Just reimaged using "volumio-2.118-2017-03-07-pi.img" and added the plugin and everything works great.  thanks!

Only thing I noticed is that when adding the plug in the date was still:

"Updated: 15-10-2016"

Cheers.

**Comment by iamsi** [comment]
confirm this works for me too. Thanks!

**Comment by macmpi** [comment]
We can certainly close this one now. Thanks.
