### ISSUE TITLE
[FEATURE] Yamaha Network Receiver

### ISSUE THREAD

**Issue by tiboudju** [volumio/volumio-plugins#57]
Hello,

I recently found a Yamaha nodejs module : https://www.npmjs.com/package/yamaha-nodejs
It works great on my RN-301 and should work with every Yamaha Receiver.
It would be great to be able to use it as a Volumio plugin, but I'm too bad to achieve it...

Maybe someone has the motivation and skills to do it ? :)

**Comment by crisp00** [comment]
Hi @tiboudju , the best place to post plugin suggestions and requests is the [forum](https://volumio.org/forum/), in case you haven't posted there yet!

**Comment by tiboudju** [comment]
Done ! ;)
