### ISSUE TITLE
Clear and Play broken since version 2.129

### ISSUE THREAD

**Issue by dinojr** [volumio/volumio-plugins#58]
Since the last upgrade, Clear and Play doesn't play anymore... Play still works though.

**Comment by crisp00** [comment]
Hi, what exactly is it that doesn't work? What behaviour are you receiving?

**Comment by dinojr** [comment]
Cris Pintea <notifications@github.com> writes:

> Hi, what exactly is it that doesn't work? What behaviour are you receiving?

When I browse to an album and select "Clear and play", the currently
playing playlist is cleared but the album is not added and the playlist
remains empty.

**Comment by crisp00** [comment]
@dinojr the problem has been fixed, it will work in the next updates! Thank you for reporting it!
