### ISSUE TITLE
Youtube plugin search does not seem to work at all

### ISSUE THREAD

**Issue by sorin-pop** [volumio/volumio-plugins#91]
Youtube plugin search does not seem to work at all

**Comment by sla89** [comment]
Can you please give more details about your setup and volumio version? I have it running on raspberry pi 3 with latest volumio and everything works fine.

**Comment by sla89** [comment]
@sorin-pop friendly ping

**Comment by sorin-pop** [comment]
Hi, I'm sorry for the late reply. I have the same setup and I think last time I used it it was working fine. Anyway it's not important for me anymore, as I got myself a second raspberry pi 3 with LibreElec+Kodi+Youtube addon for Kodi, so I am rather using Youtube from that one now. Still using the Volumio Pi for only-audio stuff though (web radios, spotify, etc.).

Thanks for your assistance. I am closing the ticket as per the above.
